# Generated by Django 2.0.5 on 2018-05-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='data_expiracao',
            field=models.DateField(blank=True, db_column='DTEXPIRACAO', null=True, verbose_name='Data Expiração'),
        ),
    ]
