# Generated by Django 2.0.5 on 2018-05-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20180513_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='email',
            field=models.CharField(db_column='EMAIL', max_length=70, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='login',
            field=models.CharField(db_column='LOGIN', max_length=15, unique=True, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='celular',
            field=models.CharField(db_column='CELULAR', max_length=15, unique=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.CharField(db_column='EMAIL', max_length=70, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='login',
            field=models.CharField(db_column='LOGIN', max_length=15, unique=True, verbose_name='Login'),
        ),
    ]
