# Generated by Django 2.0.5 on 2018-05-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_column='TITULO', max_length=30, unique=True)),
                ('descricao', models.CharField(blank=True, db_column='DESCRICAO', max_length=60, null=True)),
                ('conteudo', models.CharField(blank=True, db_column='CONTEUDO', max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, db_column='TIPO', max_length=18, null=True)),
                ('extras', models.CharField(blank=True, db_column='EXTRAS', max_length=180, null=True)),
                ('idprofessor', models.ForeignKey(db_column='IDPROFESSOR', on_delete=True, to='contas.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Atividadevinculada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idatividade', models.IntegerField(db_column='IDATIVIDADE')),
                ('rotulo', models.CharField(db_column='ROTULO', max_length=5)),
                ('status', models.CharField(db_column='STATUS', max_length=20)),
                ('iddisciplinaofertada', models.ForeignKey(db_column='IDDISCIPLINAOFERTADA', on_delete=True, to='curriculo.Disciplinaofertada')),
                ('idprofessor', models.ForeignKey(db_column='IDPROFESSOR', on_delete=True, to='contas.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_column='TITULO', max_length=30)),
                ('resposta', models.CharField(db_column='RESPOSTA', max_length=200)),
                ('dtentrega', models.DateTimeField(db_column='DTENTREGA')),
                ('status', models.CharField(db_column='STATUS', max_length=15)),
                ('idprofessor', models.IntegerField(blank=True, db_column='IDPROFESSOR', null=True)),
                ('nota', models.SmallIntegerField(blank=True, db_column='NOTA', null=True)),
                ('dtavaliacao', models.DateField(blank=True, db_column='DTAVALIACAO', null=True)),
                ('obs', models.CharField(blank=True, db_column='OBS', max_length=90, null=True)),
                ('idaluno', models.ForeignKey(db_column='IDALUNO', on_delete=True, to='contas.Aluno', unique=True)),
                ('idatividadevinculada', models.ForeignKey(db_column='IDATIVIDADEVINCULADA', on_delete=True, to='restrito.Atividadevinculada')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacaomatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtsolicitacao', models.DateTimeField(db_column='DTSOLICITACAO')),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=10, null=True)),
                ('idaluno', models.ForeignKey(db_column='IDALUNO', on_delete=True, to='contas.Aluno')),
                ('idcoordenador', models.ForeignKey(blank=True, db_column='IDCOORDENADOR', null=True, on_delete=True, to='contas.Coordenador')),
                ('iddisciplinaofertada', models.ForeignKey(db_column='IDDISCIPLINAOFERTADA', on_delete=True, to='curriculo.Disciplinaofertada')),
            ],
        ),
    ]
