# Generated by Django 2.0.5 on 2018-05-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='NOME', max_length=30, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='NOME', max_length=30, unique=True, verbose_name='Nome')),
                ('data', models.DateTimeField(blank=True, db_column='DATA', null=True, verbose_name='Data')),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=7, null=True, verbose_name='Status')),
                ('plano_ensino', models.CharField(blank=True, db_column='PLANOENSINO', max_length=8000, null=True, verbose_name='Plano de Ensino')),
                ('carga_horaria', models.SmallIntegerField(db_column='CARGAHORARIA', verbose_name='Carga Horária')),
                ('competencias', models.CharField(blank=True, max_length=450, null=True, verbose_name='Competencias')),
                ('habilidades', models.CharField(blank=True, max_length=500, null=True, verbose_name='Habilidades')),
                ('ementa', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ementa')),
                ('conteudo_programatico', models.CharField(blank=True, db_column='CONTEUDOPROGRAMATICO', max_length=1000, null=True, verbose_name='Conteúdo Programatico')),
                ('bibliografia_basica', models.CharField(blank=True, db_column='BIBLIOGRAFIABASICA', max_length=700, null=True, verbose_name='Bibliografia Básica')),
                ('bibliografia_complementar', models.CharField(blank=True, db_column='Bibliografia Complementar', max_length=700, null=True, verbose_name='Bibliografia Complementar')),
                ('percentual_pratico', models.IntegerField(blank=True, db_column='PERCENTUALPRATICO', null=True, verbose_name='Percentual Prático')),
                ('percentual_teorico', models.IntegerField(blank=True, db_column='PERCENTUALTEORICO', null=True, verbose_name='Percentual Teórico')),
                ('idcoordenador', models.ForeignKey(blank=True, db_column='idcoordenador', null=True, on_delete=True, to='contas.Coordenador')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtiniciomatricula', models.DateField(blank=True, null=True)),
                ('dtfimatricula', models.DateField(blank=True, null=True)),
                ('ano', models.SmallIntegerField(db_column='ANO')),
                ('semestre', models.IntegerField(db_column='SEMESTRE')),
                ('turma', models.CharField(db_column='TURMA', max_length=1)),
                ('idprofessor', models.IntegerField(blank=True, db_column='IDPROFESSOR', null=True)),
                ('metodologia', models.CharField(blank=True, db_column='METODOLOGIA', max_length=150, null=True)),
                ('recursos', models.CharField(blank=True, db_column='RECURSOS', max_length=150, null=True)),
                ('criterio_avaliacao', models.CharField(blank=True, db_column='CRITERIOAVALIACAO', max_length=60, null=True)),
                ('planode_aulas', models.CharField(blank=True, db_column='PLANODEAULAS', max_length=500, null=True)),
                ('idcoordenador', models.ForeignKey(db_column='IdCoordenador', on_delete=True, to='contas.Coordenador')),
                ('idcurso', models.ForeignKey(db_column='IDCURSO', on_delete=True, to='curriculo.Curso')),
                ('iddisciplina', models.ForeignKey(db_column='IDDISCIPLINA', on_delete=True, to='curriculo.Disciplina')),
            ],
        ),
    ]
