# Generated by Django 2.0.5 on 2018-05-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(db_column='NOME', max_length=100, verbose_name='Nome'),
        ),
    ]
