# Generated by Django 2.0.5 on 2018-05-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0003_auto_20180513_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(db_column='NOME', max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
